name: CI

on:
    pull_request:
        branches: ['*']
    push:
        branches: [master]
    merge_group:
    workflow_dispatch:

jobs:
    ci:
        strategy:
            matrix:
                node: [18, 20, 22]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v3

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                  echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install deps (with cache)
              run: pnpm install

            - name: Check format
              run: pnpm format:check

            - name: Run eslint
              run: pnpm lint

            - name: Run typecheck
              run: pnpm typecheck

            - name: Run build
              run: pnpm build

            - name: Run tests
              run: pnpm test -- --coverage

            - name: Report Coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
